name: Vulnerability Check

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 6 * * 1'

permissions:
  contents: read

jobs:
  govulncheck:
    runs-on: [self-hosted]
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Go
        uses: ./.github/workflows/go-setup

      - name: Run govulncheck
        uses: golang/govulncheck-action@b625fbe08f3bccbe446d94fbf87fcc875a4f50ee # v1.0.4
        with:
          output-format: sarif
          output-file: govulncheck.sarif

      - name: Upload SARIF to code scanning
        if: always()
        uses: github/codeql-action/upload-sarif@7fd177fa680c9881b53cdab4d346d32574c9f7f4 # v3.35.4
        with:
          sarif_file: govulncheck.sarif
          category: govulncheck
